name: Upload .obj Files to Release

on:
  release:
    types: [created]

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Upload arquivos .obj
        uses: softprops/action-gh-release@v1
        with:
          files: "models/*.obj"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
